#cloud-config
users:
  - name: ${username}
    groups: sudo
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh_authorized_keys:
    - ${ssh_key}
write_files:
  - path: /etc/profile.d/my-env-var.sh
    permissions: '0644'
    content: |
      export SERVER_URL="http://${username}:8111"